commits:
  - sha: 240a9f361186f245478ad585e86d02796f9ff73b
    commit:
      author:
        name: Mark Chavez
        email: markchav3z@gmail.com
        date: "2017-04-07T07:08:48Z"
      committer:
        name: Mark Chavez
        email: markchav3z@gmail.com
        date: "2017-04-07T07:08:48Z"
      message: Commit number 1
      html_url: https://github.com/cloudhealthkinnect/cloudhealth/commit/240a9f361186f245478ad585e86d02796f9ff73b
      author:
        login: mrkjlchvz
    committer:
      login: mrkjlchvz

  - sha: 20394ulskfj023rujfksjf2-fjlkjfsd6f9ff73b
    commit:
      author:
        name: Mark Chavez
        email: markchav3z@gmail.com
        date: "2017-04-07T07:08:48Z"
      committer:
        name: Mark Chavez
        email: markchav3z@gmail.com
        date: "2017-04-07T07:08:48Z"
      message: Commit number 2
      html_url: https://github.com/cloudhealthkinnect/cloudhealth/commit/240a9f361186f245478ad585e86d02796f9ff73b
      author:
        login: mrkjlchvz
    committer:
      login: mrkjlchvz
