# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d4b6b327f6b5c695121073183554e61f0d390235572a443abfb5cb3a61304e98db3b81d33e09783e0f361317c03dbff84366bf3552f6ea1758fe3b08726d3a
  gh_client_key: 8dc662678f53b6944f15
  gh_client_secret: a2bda626e440d48ea62448ca980ab75f2517b4b1

test:
  secret_key_base: 9be2ed975f2c193978f24ea10b8fdb4707e156b47e2e5e1765c13facf4858efb480a88be4b4aa44f0b3338af12b186fad7d38859a608abf29cf99ee86b9b8925
  gh_client_key: 8dc662678f53b6944f15
  gh_client_secret: a2bda626e440d48ea62448ca980ab75f2517b4b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gh_client_key: <%= ENV["GH_CLIENT_KEY"] %>
  gh_client_secret: <%= ENV["GH_CLIENT_SECRET"] %>

